apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - sideEffects: None
    admissionReviewVersions:
      - v1
      - v1beta1
    name: webhook.default.svc
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: "/webhook"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXlNREF5TVRBME9Gb1hEVE16TURReE56QXlNVEEwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUJRCk4zK2VMMlVDR3lTNGRWQzBRelpjVU03T0NKUVBzMU8vSDZnbFdKVTBEVHNhcWd0UldVNEo2TU5NV3B6MUxNencKUkZJN2cvYWJSelZQUC9Ua0U1dTRhS1NsZDAxWUtKZVV4aGVnc3d6WE9ZY3Y1cHkvYUhGbG9zZ1YyTFFFaHo3WApwWVRmVVBPNHppME5MU2prSGFSOWV4VHR1SnJZcll0VnRkWVVORTYyYitZaEJjcUpRTUhWVURudTIwRm9lN0wwCll5eDlpN1l1clc4WGdCS2ZhTU4zTWx6Sm1QcUFmSFBoWkNPQk0xMG9TMzN2SXJnR3BNaWpEaFJwelh0aE9pSDEKWUI4dzNKR1dJcjA5c3BmOU50emRudkwxS1M5VFM5ODVhVlRLZno5WCt1alBaSitiV0trVmRTZWpzN09MYVJqeAp2dW53aDBCSVlzTHRkN3ZXamZjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQUmsyeE0xRUQrN1VseG16ZzdxOHRncFRyclVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSEJJVjZVRmNuN1dCY28wRzZXVgpBeUdBNFVla204eUVhT0JMRWxOYW9aQTVIV0ZKQy9OS0d6b3NlbzBqZ1hPK1IvdGx3OTJtTDZMam1JNmVhQXhtCjA2SlhsSWJmekFBYjJMa21vWDJjQ0lybi9hL2VkUUhhTEZjQ1JRSDEyRE5mNGEzdGVOQlBMRSt1dmVUbWRwbm4KTHlWYWJqV3V4UVdPVDdxRG04cDREV1VsNlFtQjNiRkd2b2JOQ25UQi8xeUVUdXd5RTExRnRHYlhaS1BkV2FTZAovN252UFFWZEVXeTFzK050UUYvVEUycWRJSXByVUlibUp5OFM0dHlhOXJ5QTdDbEZCNVYyaVZ4RStrMW9mSytLCkZiN24zeVh0d0pXQks0UnA3cEZhbnBaVUJUQlV5MXp5Q2dGQVJRTFJHRUllbnBCaHd2eko2Mi9CazVIZGtjZk0Kd0VvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "UPDATE" ]
        apiGroups: [ "*" ]
        apiVersions: [ "v1" ]
        resources: [ "nodes/status"]